spring:
  application:
    name: eureka-server

server:
  port: 8000

eureka:
  instance:
    hostname: eurekaPeer1
  client:
    service-url:
      defaultZone: http://eurekaPeer1:8000/eureka/
    fetch-registry: false #注册服务不需要从注册中心获取信息
    register-with-eureka: false #注册服务不需要把自己注册到注册中心
  server:
    enable-self-preservation: true #自我保护机制，默认开启
    renewal-percent-threshold: 0.85 #默认0.85

